name: fit_friends
services:
  fit_friends.postgres:
    image: postgres:14-alpine
    container_name: fit_friends.postgres
    restart: always
    env_file:
      - ./api.env
    ports:
      - 5431:5432
    volumes:
      - fit_friends.postgres:/postgresql/data

    networks:
      - fit_friends

  fit_friends.backend:
    image: fitfriends-backend:v.2.0
    container_name: fit_friends.backend
    restart: always
    depends_on:
      - fit_friends.postgres
    env_file:
      - ./api.env
      - ./account.env
      - ./file.env
    ports:
      - 3000:3000
    networks:
      - fit_friends


volumes:
  fit_friends.postgres:

networks:
  fit_friends:
      driver: bridge
