#add friend
POST http://localhost:3000/friends/0e7586f4-3f28-439e-a4ca-647226d8482a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTViNWZhYy1jZTM4LTRkYTAtYmMzOS1kMGYzMTUxMzQ1Y2QiLCJuYW1lIjoiU0oiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMzY2MTMxNiwiZXhwIjoxNzMzNjYyMjE2fQ.AI6-mFjYtf3vtMY0la6wowOyn-avquz5aOM70lNPA1g

{
}

###

#delete friend
DELETE http://localhost:3000/friends/012b8e7f-99eb-49aa-9fd4-02a2d4104eb9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTViNWZhYy1jZTM4LTRkYTAtYmMzOS1kMGYzMTUxMzQ1Y2QiLCJuYW1lIjoiU0oiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMzY2MTMxNiwiZXhwIjoxNzMzNjYyMjE2fQ.AI6-mFjYtf3vtMY0la6wowOyn-avquz5aOM70lNPA1g

###

#get friends list
GET http://localhost:3000/friends?count=2&page=3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTViNWZhYy1jZTM4LTRkYTAtYmMzOS1kMGYzMTUxMzQ1Y2QiLCJuYW1lIjoiU0oiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMzY2MTMxNiwiZXhwIjoxNzMzNjYyMjE2fQ.AI6-mFjYtf3vtMY0la6wowOyn-avquz5aOM70lNPA1g

###
