# Create new training

POST http://localhost:3000/trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOTI5MGI0Ny02OTA1LTRjMWYtYmQ5Zi02NWUzM2RiNTdjMzciLCJuYW1lIjoiVGVkIExhc3NvIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNzM0Mzk4NTE3LCJleHAiOjE3MzQzOTk0MTd9.W4GllxbN7uWUZ5Nm16YXaBuvljBV1QKHr7aqs1ye7po

{
  "title": "Email test 9",
  "level": "любитель",
  "type": "пилатес",
  "duration": "10-30 мин",
  "price": 1000,
  "callorieQuantity": 2000,
  "description": "Efficiently cultivate distinctive manufactured products without premium initiatives. Completely.",
  "gender": "неважно",
  "isSpecialOffer": false
}

###

# Get All trainings

GET http://localhost:3000/trainings?count=50&page=1&filterBy=coach HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2VhYmQxZi0wNGM5LTQyZDQtOWNjOS00NGE4Y2ZiMGYwMjEiLCJuYW1lIjoiVGVkIExhc3NvIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNzMwNzI2MjI4LCJleHAiOjE3MzA3MjcxMjh9.56uM_XNT8ohxlbubf_o5MDPGVSdGAJjPLBNcEoDsRVU

###

# Get specific training

GET http://localhost:3000/trainings/95b84a04-25eb-4210-96fc-0fd8b6c2b98a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2VhYmQxZi0wNGM5LTQyZDQtOWNjOS00NGE4Y2ZiMGYwMjEiLCJuYW1lIjoiVGVkIExhc3NvIiwicm9sZSI6ImNvYWNoIiwiaWF0IjoxNzMwNTYxODI1LCJleHAiOjE3MzA1NjI3MjV9.bqRh1RyPZDoaxLOEzOnuQJxQvSLVrKKUovUO4AS4EKU

###
