#create a new user
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
  "email": "ted@mail.com",
  "name": "Ted Lasso",
  "password": "111111",
  "gender": "неважно",
  "birthDate": "23.03.1990",
  "description": "Assertively architect frictionless processes rather than enterprise-wide testing procedures.",
  "location": "Пионерская",
  "role": "user"
  }

###

#Get user by id
GET http://localhost:3000/user/f9efcba0-3bc2-49a0-bab2-1c02bf25ae33 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOWVmY2JhMC0zYmMyLTQ5YTAtYmFiMi0xYzAyYmYyNWFlMzMiLCJuYW1lIjoiUm9uYWxkIiwiaWF0IjoxNzI4NDQ5MjI5LCJleHAiOjE3Mjg0NTAxMjl9.xQd_YXveCdZUAj72RNZPR4qw0dqIN51Mg9cpy5J7LQA

###

#Login user
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "sj@example.com",
  "password": "111111"
}

###


#Refresh tokens
POST http://localhost:3000/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjY0YTNkYy00ZjI3LTRjY2EtYmMxOS05YTkyMWU2YjdlOTkiLCJuYW1lIjoiUm9uYWxkIiwidG9rZW5JZCI6ImIxMTA0ZmMyLTVjMWItNDFmMC04ODk2LWI0ODE4ZDYxOWJmYSIsImlhdCI6MTcyODM0MTQ4OSwiZXhwIjoxNzI4OTQ2Mjg5fQ.eoks70A2_UiG1kiy_JvOaNeTJnxfWY8rtc5qQJr40Js

###

# Check user token
POST http://localhost:3000/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjY0YTNkYy00ZjI3LTRjY2EtYmMxOS05YTkyMWU2YjdlOTkiLCJuYW1lIjoiUm9uYWxkIiwiaWF0IjoxNzI4MzQxNDg5LCJleHAiOjE3MjgzNDIzODl9.B_OxqaDOmdbiBqXlyjy7-YhH399OBrvdy-_8RIo34vY

###

# Update
POST http://localhost:3000/user/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2VhYmQxZi0wNGM5LTQyZDQtOWNjOS00NGE4Y2ZiMGYwMjEiLCJuYW1lIjoiVGVkIExhc3NvIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzA1NjE0MDksImV4cCI6MTczMDU2MjMwOX0.ZGLqAF0zjbLFd8L04hqQcmDjI5nq4ToSxnNNpoi7NWw

{
  "role": "coach"
}

###

# Logout
DELETE http://localhost:3000/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjY0YTNkYy00ZjI3LTRjY2EtYmMxOS05YTkyMWU2YjdlOTkiLCJuYW1lIjoiUm9uYWxkIiwiaWF0IjoxNzI4MzQxNDg5LCJleHAiOjE3MjgzNDIzODl9.B_OxqaDOmdbiBqXlyjy7-YhH399OBrvdy-_8RIo34vY


###

# Get all users
GET http://localhost:3000/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNTViNWZhYy1jZTM4LTRkYTAtYmMzOS1kMGYzMTUxMzQ1Y2QiLCJuYW1lIjoiU0oiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMzM3NTMyOSwiZXhwIjoxNzMzMzc2MjI5fQ.db6h0aCvryEXdIrlyE5jtEkMJcBqAtcpybvNR9EGHnQ

###
