# Create new Review

POST http://localhost:3000/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjJmYmFmYS02MGRlLTRkMzgtOWRlYi01OWIzNTRjYWJjZjgiLCJuYW1lIjoiRG91Z2xhcyBLb2NoIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MzA1NjIzNTMsImV4cCI6MTczMDU2MzI1M30.AOycKxf_glmGNFWb6pJIxtreybE8aKTichi51kG-NW8

{
  "trainId": "95b84a04-25eb-4210-96fc-0fd8b6c2b98a",
  "content": "Objectively empower leveraged infomediaries after error-free experiences. Interactively re-engineer.",
  "rate": 5
}
###

# Get all reviews of specific training

GET http://localhost:3000/reviews/714761d7-2535-4edb-99f1-906b4ec71f4f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOWVmY2JhMC0zYmMyLTQ5YTAtYmFiMi0xYzAyYmYyNWFlMzMiLCJuYW1lIjoiUm9uYWxkIiwiaWF0IjoxNzI4NDQzNTc4LCJleHAiOjE3Mjg0NDQ0Nzh9.2uM0B2RXHcaL0ylMrY1Myk3kH-WNWkX89uH5pvfe9tI

###
