services:
  notification.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "notification.fakesmtp"
    hostname: "notification.fakesmtp"
    ports:
      - "8025:8025"
      - "1085:8080"

  notification.rabbitmq:
      image: rabbitmq:3.11-management
      container_name: notification.rabbitmq

      ports:
        - '1088:15672'
        - '5672:5672'

      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 5s
        retries: 5

